### ISSUE TITLE
Login and Register not work

### ISSUE THREAD

**Issue by ghost** [didierdemaeyer/laravel-multiple-locales#2]
Hello
I install this package by using instruction now when I click on http://domain.com/login it go to http://domain/en
Also 
http://domain/product/1/ will go to http://malahem/en/1/

How can I fix this issue.

**Comment by jorenvh** [comment]
Did you run the install command?

php artisan multiple-locales:install

It generates a new RouteServiceProvider witch prefixes all your routes with the local.

You can also add routes that you don't want to translate in the skip_locals array in config/app.php

**Comment by ghost** [comment]
I rerun command and I get:The multiple locales package is already installed!
When I use:{{ url(config('app.locale').'/product',[$product->id,$product->code]) }} 
I don't get any error.

**Comment by jorenvh** [comment]
What is the content of your RouteServiceProvider file?

**Comment by ghost** [comment]
`<?php

namespace App\Providers;

use Illuminate\Http\Request;
use Illuminate\Routing\Router;
use Illuminate\Foundation\Support\Providers\RouteServiceProvider as ServiceProvider;

class RouteServiceProvider extends ServiceProvider
{
    /**
     \* This namespace is applied to the controller routes in your routes file.
     *
     \* In addition, it is set as the URL generator's root namespace.
     *
     \* @var string
     */
    protected $namespace = 'App\Http\Controllers';

```
/**
 * Define your route model bindings, pattern filters, etc.
 *
 * @param  \Illuminate\Routing\Router  $router
 * @return void
 */
public function boot(Router $router)
{
    parent::boot($router);
}

/**
 * Define the routes for the application.
 *
 * @param  \Illuminate\Routing\Router $router
 * @param Request $request
 */
public function map(Router $router, Request $request)
{
    $locale = $request->segment(1);

    if (in_array($locale, $this->app->config->get('app.skip_locales'))) {
        $this->skippedLocaleRoutes($router);
        $locale = $this->app->config->get('app.locale');
    } else {
        $this->localeRoutes($router, $locale);
    }
    $this->app->setLocale($locale);
}

/**
 * Add a locale prefix to routes
 * @param  \Illuminate\Routing\Router $router $router
 * @param  string $locale
 * @return void
 */
private function localeRoutes($router, $locale)
{
    $this->app->setLocale($locale);

    $router->group(['namespace' => $this->namespace, 'prefix' => $locale], function ($router) {
        require app_path('Http/routes.php');
    });
}

/**
 * Map routes without locale prefix
 * @param  \Illuminate\Routing\Router $router
 * @return void
 */
private function skippedLocaleRoutes($router)
{
    $router->group(['namespace' => $this->namespace], function ($router) {
        require app_path('Http/routes.php');
    });
}
```

}
`

**Comment by jorenvh** [comment]
The language package is url based so just add your language is the first parameter in the url. Ande make sure the locale is added to your config/app.php file. 

The package always takes the first segment as the locale. If it is not found it resirects to the defailt locale, en in your case

So the package works as it should.

Joren

**Comment by ghost** [comment]
How ca I check my config/app.php?
In login and register page I get this error:
Undefined variable: errors (View: C:\xampp\htdocs\XXX\resources\views\auth\register.blade.php)

**Comment by jorenvh** [comment]
Through your code editor?

**Comment by ghost** [comment]
No, In web page 
http://domain/en/login
and
http://domain/en/register

I use laravel auth and I have Route::auth() in routes.php

**Comment by jorenvh** [comment]
You can't check your config files throug your browser. But I suggest you post your question ar stackoverflow beceaue it is not related to this package.

Best or luck and kind regards,
Joren

**Comment by ghost** [comment]
Thanks,
But after I remove your package anything work fine.

**Comment by didierdemaeyer** [comment]
Joren's answer is correct.

It looks like you don't want the login and product routes to be multi language, so you should add 'login' and 'product' to the skip_locales array in your app.php file located in your_project_name/config/

I hope this solves your problem.

Didier

**Comment by ghost** [comment]
I recheck my routes and config/app
I have problem with built-in auth.

I think there is problem with Route:auth();

**Comment by ghost** [comment]
Solved just add routes in:
`Route::group(['middleware' => ['web']], function () {});`
